language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
after_success:
 - cd dist/
 - git init .
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis"
 - git remote add origin https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git
 - git checkout -b gh-pages
 - git add --all -f .
 - git commit -a -m "Travis - ${TRAVIS_BUILD_NUMBER}"
 - git push --force origin gh-pages
